name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
          
      - name: Build, run unit tests, and run Lint
        run: ./gradlew --no-daemon build lint -x connectedAndroidTest

      - name: Upload Lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: "**/build/reports/lint-results-*.html"
          retention-days: 7